### ISSUE TITLE
Error message "unpack requires a buffer of 20 bytes" when opening plugin

### ISSUE THREAD

**Issue by rkfmiller** [danioxoli/HotSpotAnalysis_Plugin#10]
Hello - I am new to both QGIS and python. I am trying to run the hotspot analysis tool on Mac version 10.11.6, QGIS version 3.2.2. I have successfully installed the hotspot plugin for QGS3, however whenever I open the tool from the vector drop-down menu I receive the following error message:

"An error has occurred while executing Python code: 

struct.error: unpack requires a buffer of 20 bytes"

The hotspot analysis window does pop up after this message, and I can select a layer for analysis and provide the relevant details, however nothing happens after selecting "OK." I've attached screenshots of my version of QGIS and the error message.
![screen shot 2018-09-12 at 3 20 46 pm](https://user-images.githubusercontent.com/43222431/45456425-8c051a00-b69f-11e8-91ff-fc4f3e2acd0d.png)
![screen shot 2018-09-12 at 3 19 16 pm](https://user-images.githubusercontent.com/43222431/45456426-8c051a00-b69f-11e8-9eae-631c06eb1f4d.png)

**Comment by danioxoli** [comment]
Dear rkfmiller;
 
Thank you for your interest!

Actually, it's the first time that I see this specific error. By assuming your input shapefile correct, this looks like an internal error of pysal and pyshp. Have you tried to update PySAL after updating also the pip?
Do like:
`python3.6 -m pip install --upgrade pip`
`pip3 install --upgrade  pysal`

Often, dependency version causes such minor conflicts when installing separately. 

Let me know if this fixes your issue.

Best,

Daniele
