### ISSUE TITLE
'Bad Gateway' during install

### ISSUE THREAD

**Issue by ThirstyGeo** [danioxoli/HotSpotAnalysis_Plugin#12]
I think there may be a stale download link:

Plugin installation failed: Error transferring https://plugins.qgis.org/plugins/HotspotAnalysis/version/1.0.1/download/ - server replied: Bad Gateway

This is a great plugin, by the way!

**Comment by danioxoli** [comment]
Hi and thank you for your interest!

I do not control the distribution of the plugin through the QGIS official repo... Anyway, It might be due to a temporary stop of the server because now the link seems to work!

Best

Daniele
