### ISSUE TITLE
TOO MANY VALUES TO UNPACK

### ISSUE THREAD

**Issue by GiuliaT** [danioxoli/HotSpotAnalysis_Plugin#20]
Hi Daniele,

the new problem concerns the form of my point vector, in which I have the following fields:

reg_code String 254 0
latitude Real 23 15
longitude Real 23 15
_freq Integer64 10 0

Here in the picture:
![image](https://user-images.githubusercontent.com/45032201/48547570-3cbfad80-e8cb-11e8-8b97-3e5f2c9bf937.png)

I am not able to perform hotspot analysis on this layer as it returns me the following error: 
2018-11-15T11:35:19     WARNING    Traceback (most recent call last):
File _"C:/Users/giugg_000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 564, in run (path, layer_id) = layerName.split('|') ValueError: too many values to unpack (expected 2)_

Do you how could I solve this problem?

Best,
Giulia

**Comment by danioxoli** [comment]
It looks like a problem in the file name or path which you are using to store the output. 
Can you share with me the layer, the path string and layer name you are using? (daniele.oxoli@polimi.it)
I will try to check

Daniele
