### ISSUE TITLE
error using demo data

### ISSUE THREAD

**Issue by rfernan6ASU** [danioxoli/HotSpotAnalysis_Plugin#24]
I tried using the demo data provided in this Qgis3 branch. 

Although the plugin initiated without any errors, the following warning appeared in the python error log while trying to use the shapefile with points: 

![image](https://user-images.githubusercontent.com/47647746/52987316-335d4a00-33c0-11e9-9562-e44bea6e844b.png)

Would you please advice on this error? 

Cheers!

Rafa

**Comment by danioxoli** [comment]
Try to refresh the plugin or close and re-open a new QGIS project and load the data. Be sure that the demo data folder is properly uncompressed on your machine while you are using it as data source.

If you get the same, this is probably due to the version of PySAL you are using. 

The specific API that produces the default distance is part of version <= 1.4 (see instruction), not sure I was kept with the same name in higher versions.

Let me know!

Daniele

**Comment by rfernan6ASU** [comment]
Hi, Danilele.

I installed PySAL 1.14. and refreshed the plugin as advice. However, the error remains.

2019-02-26T08:57:53     WARNING    Traceback (most recent call last):
              File "/Users/Rafael/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 551, in run
              self.load_comboBox()
              File "/Users/Rafael/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 472, in load_comboBox
              thresh = pysal.min_threshold_dist_from_shapefile(path)
             AttributeError: module 'pysal' has no attribute 'min_threshold_dist_from_shapefile'

I am not completely sure 1.4 substituted 2 because when i ask for the version in terminal it keeps showing pysal 2. What should I do? Is there any way to downgrade from pysal 2 to 1.4? 

![image](https://user-images.githubusercontent.com/47647746/53423046-3b138480-39a6-11e9-9028-6cceef7e74bd.png)

Thank you very much for your patience!!!

Rafa

**Comment by danioxoli** [comment]
Hi Rafa,

It looks like pysal 1.14 do not overwrite the existing 2.0 version.
Try with something like:

`sudo pip3 install --upgrade --no-deps --force-reinstall pysal==1.14.3 `

Let me know if this solves the problem!

Best

**Comment by rfernan6ASU** [comment]
Dear Daniele,

It worked.  Oh so satisfying!  :D 

I finally was able to use the plugin with the demo data– both points and poligons—without errors. I'll give it a shot with my own data to see how it goes. I promise to catch up with the literature so I can get a tad more acquainted with the math and rationale of the tool. I'll keep you posted. 

Again, thank you very much for all your help and patience. 

Best

Rafa 

![image](https://user-images.githubusercontent.com/47647746/53504007-c5c3b480-3a76-11e9-92ff-0b5a64c8b989.png)

**Comment by danioxoli** [comment]
Good, 

I'm gonna close the issue.
Thank you for reporting. I hope in the next months to find time to embed PySAL in the plugin code and solve these dependency issues!

Best,

Daniele
