### ISSUE TITLE
Document numpy.random.seed(12345)

### ISSUE THREAD

**Issue by kannes** [danioxoli/HotSpotAnalysis_Plugin#32]
https://github.com/danioxoli/HotSpotAnalysis_Plugin/blob/2120fcd80c8240a9a2546032dbc78dae38f09bed/hotspot_analysis.py#L618 says

`numpy.random.seed(12345)`

Please add some documentation as to why a fixed random seed is set there.

**Comment by danioxoli** [comment]
I believe that the concept of random seed is a bit far from the interest of standard users. Of course, this is introduced to obtain equal results at each Plugin run when using the same data and settings,   and it's a common pattern when using random number generators. 

Daniele
