### ISSUE TITLE
Migration to PySAL 2 requires changes

### ISSUE THREAD

**Issue by kannes** [danioxoli/HotSpotAnalysis_Plugin#33]
The plugin does not work with PySAL 2 which is what people will get from PyPi since January 2019.

Please consider https://github.com/pysal/pysal/blob/master/MIGRATING.md for a migration guide.

**Comment by danioxoli** [comment]
migration has started on this branch: https://github.com/danioxoli/HotSpotAnalysis_Plugin/tree/qgis3pysal2
