### ISSUE TITLE
Document restriction to ESRI Shapefile format

### ISSUE THREAD

**Issue by kannes** [danioxoli/HotSpotAnalysis_Plugin#34]
This plugin seems to only support ESRI Shapefiles, not anything in loaded in QGIS with QGIS' abstractions. Please document that prominently, e.g. with a note in the plugin description.

I tested with both a GeoPackage and a GML layer, there were not displayed in the plugin's dropdown layer chooser.

**Comment by danioxoli** [comment]
Dea Kannes,

the exclusive support of Shapefile is clearly states in the current plugin description:


`The Plugin implements Local Indicators of Spatial Association (LISA) statistics to perform the Hotspot (Getis-Ord Gi*) and Clusters (Moran's I) analysis and links them to maps. Input data must be a shapefile of points or polygons with an associated projected coordinate system and (at least) one numeric attribute. The plugin requires Pysal (see the repository for installation instruction).`


I hope soon to have time to extend the I/O capabilities of the plugin to overcome these issues.

Best,

Daniele

**Comment by kannes** [comment]
Hey Daniele, I did not notice that and people tend to use the term "shapefile" ambigiously. Maybe you could add linebreaks to the text and write "ESRI Shapefile" or "Shapefile", that should make it more clear.

**Comment by danioxoli** [comment]
Thank you, I will!
