### ISSUE TITLE
module 'pysal' has no attribute 'knnW_from_array'

### ISSUE THREAD

**Issue by z7ye** [danioxoli/HotSpotAnalysis_Plugin#38]
I tried different version of pysal, none of them has attributes knnW_from_array or spreg. Please help.

**Comment by danioxoli** [comment]
Hello,

can you please share more info on your OS and QGIS version?

According to what you stated, It looks like your QGIS is using a version of pysal > 2 and you need to downgrade to version 1.14.

Daniele
