### ISSUE TITLE
issue installing plugin

### ISSUE THREAD

**Issue by eperez4** [danioxoli/HotSpotAnalysis_Plugin#42]
When I try to install the HotSpotAnalysis Plugin I get the error: "ModuleNotFoundError: No module named 'Shape'" I have redownloaded pysal and the shapes module several times to confirm that they are in the correct locations. Any suggestions on how to troubleshoot this error?

**Comment by danioxoli** [comment]
I would like to point you directly on this page: https://github.com/pysal/pysal/issues/693: 

> That error can happen when you install with pip that is from python 2x but then try to import pysal when running python 3x.

I encountered the same issue once using Python 2 and I solved by uninstalling pysal and reinstalling using:

`pip install --no-cache-dir pysal=1.14`

However, the trick not always works (see eg issue #15 )...

Let me know if this was helpful!

Best,

Daniele
