### ISSUE TITLE
Input layer of Interest Not Shown

### ISSUE THREAD

**Issue by yuwaedomwande** [danioxoli/HotSpotAnalysis_Plugin#53]
Hello, 

I've created a new layer within the project, but it is not shown as an option when I attempt to use the plugin. Is this because some counts in each a polygon are zero?

Thanks for your help.

**Comment by danioxoli** [comment]
Hello,

Is the layer a virtual one? In this case, you should save it as a shapefile in your drive and use that as input. Zero counts are fine, only missing data in the attribute field prevent the plugin to work (if this is your case, you should substitute missing data with zeros, for examples).

Best,

Daniele

**Comment by yuwaedomwande** [comment]
Fantastic. Saving as a shape file did the trick. Thanks so much!
