### ISSUE TITLE
Cannot Use Plugin for Multiple Layers in Project

### ISSUE THREAD

**Issue by yuwaedomwande** [danioxoli/HotSpotAnalysis_Plugin#56]
Hello, 

I can use the plugin a layer I created by a join operation after saving it to a shape file. When I complete another analysis with another layer, the first analysis I completed changes to match the new analysis even though the layers are different. In the end, after using the plugin with my three layers of interest, they all look the same as the last layer even though they did not when I initially focused on the first two layers. Does the plugin allow for multiple analyses within the same project?

Thanks.

**Comment by danioxoli** [comment]
In principle, each run of the plugin is independent and acts only on the specified input layers each time. Can you provide more info about this issue as I am not sure to have completely understood?

**Comment by yuwaedomwande** [comment]
Certainly. I first run the plugin with on my first shape file of interest and I get an output with no errors. I use the plugin again on another completely separate shape file for another output. If I return to the very first hotspot output with my first layer, it changes to look exactly the same as the second output I just created. The first output I create does not save and updates to any subsequent map I create. Basically all of the outputs change to the subsequent output. I hope this is more clear.

**Comment by danioxoli** [comment]
I have tried to replicate by using two separate copies of the test data (polygon) and I did not encounter the issue. Are you saving the output by specifying the full path at each run? (as this looks like an unwanted overwriting of the output layer)

best,
Daniele

**Comment by yuwaedomwande** [comment]
Hello, 

I've just tried again, and it looks like I was just overwriting the layer as you suggested. I don't believe I was specifying the path at each run. Thanks so much.
