### ISSUE TITLE
A possible solution for error ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by miquelfm** [danioxoli/HotSpotAnalysis_Plugin#62]
I was trying to install the HotSpot analysis plugin from zip (https://github.com/danioxoli/HotSpotAnalysis_Plugin/archive/qgis3pysal2.zip), but was getting the error "ValueError: not enough values to unpack (expected 2, got 1)". 

I had installed pysal-2.0.0 as you say in https://github.com/danioxoli/HotSpotAnalysis_Plugin/tree/qgis3pysal2

I started looking through the code and managed to solve the error after modifying two lines. 

-	Line 432
(path, layer_id) = selectedLayer.dataProvider().dataSourceUri().split('|')
to
path = selectedLayer.dataProvider().dataSourceUri().split("|")[0]

-	Line 552
(path, layer_id) = layerName.split('|')
to
path = layerName.split("|")[0]

I believe the problem can be solved with this options.  
If you can confirm the solution, it would be of great help to the rest.

I look forward to hearing from you. 
Thank you

**Comment by danioxoli** [comment]
Dear,

I will have a look at your solutions which sounds. I found the same error with the new QGIS LTR version but I had not time to investigate. Let you know!

Thank you in advance!

**Comment by danioxoli** [comment]
Hello,

I've push the changes (including some improvement to the Pysal import patterns) on the Qgis3Pysal2 branch: https://github.com/danioxoli/HotSpotAnalysis_Plugin/tree/qgis3pysal2

I've tested succesfully on QGIS 3.16 (Windows). Please, let me know if this works for you too

Best

**Comment by miquelfm** [comment]
Hello,

I've tested succesfully on QGIS 3.16 (Windows) too. 

Thank you!
