### ISSUE TITLE
HotSpot Analysis Plugin does not work after installation

### ISSUE THREAD

**Issue by RafP2021** [danioxoli/HotSpotAnalysis_Plugin#63]
Hi there, 
I followed step-by-step the procedure to install the Hotspot Analysis plugin on my QGIS 3.4 LTR Hannover (Windows 10 Home).  The plugin did finally get installed without any issue, anyway, every time I try to open it, I receive the following error message:

Traceback (most recent call last):
 _File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 531, in self.dlg.comboBox.currentIndexChanged.connect(lambda: self.load_comboBox())
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 444, in load_comboBox (path, layer_id) = selectedLayer.dataProvider().dataSourceUri().split('|')
ValueError: not enough values to unpack (expected 2, got 1)_

It appears immediately, just when I open the plugin, and even before I try to run it. I tried it with polygon layers having integer and real number records and no null values, and I also put them as first in the layer list. I also tried to open the plugin with different layers and within different projects, but this message still appears, and the plugin does not work, and does not produce any output layer. 

Any clue about what am I doing wrong?
Thank you!

Raffaele

**Comment by danioxoli** [comment]
Hello,

we have to fix some bug that came with QGIS 3.16 LTR and this was done on another branch of the plugin (which is going to be released as Master soon, see here: https://github.com/danioxoli/HotSpotAnalysis_Plugin/issues/62)

Be careful that this new version requires PySAL 2.0, you can find both plugin and instructions here: https://github.com/danioxoli/HotSpotAnalysis_Plugin/tree/qgis3pysal2

Best,
Daniele

**Comment by RafP2021** [comment]
Spettacolo!!!
Ehm, I meant, Amazing! Now it works perfectly! Thank you Daniele so much!

Raffaele
